#!/bin/bash

# We really need a sane option parsing mechanism.
# This is really limited, but the alternatives I
# could find for bash are even worse from what I read.
# I'm really considering writing this in python just
# to use optparse or something.
while getopts ':d:a:' OPT
do
    case $OPT in
        a)
            ARDUINO_DIR="$(readlink -f "$OPTARG")"
            ;;
        d)
            DEST_DIR="$(readlink -f "$OPTARG")"
            ;;
        \?)
            echo "Invalid option -$OPTARG"
            exit 1
            ;;
        :)
            echo "Option $OPT requires an argument"
            exit 1
            ;;
    esac
done
# A horrible hack to get the positional arguments.
# Someone please tell me there's a better way to do
# this only I'm too stupid to find out!
ARGS=${@:$OPTIND}

if [ -z "${ARGS[0]}" ]
then
    echo "You need to provide a project name: \`$(basename $0) <project>'"
    exit 1
else
    PROJECT_NAME="${ARGS[0]}"
fi

DEST_DIR=${DEST_DIR:=$PWD}
ARDUINO_DIR=${ARDUINO_DIR:=$PWD}

WORKING_DIR="$(dirname $(readlink -f "$0"))"
SKEL="$WORKING_DIR/skel"
MAIN_MAKEFILE="$WORKING_DIR/arduino-mk/Arduino.mk"

PROJECT_DIR="$DEST_DIR/$PROJECT_NAME"

cp -r "$SKEL" "$PROJECT_DIR"
mv "$PROJECT_DIR/project.pde" "$PROJECT_DIR/$PROJECT_NAME.pde"

sed -i "s!__PROJECT_NAME__!$PROJECT_NAME!g" "$PROJECT_DIR/Makefile"
sed -i "s!__ARDUINO_DIR__!$ARDUINO_DIR!g" "$PROJECT_DIR/Makefile"
sed -i "s!__MAIN_MAKEFILE__!$MAIN_MAKEFILE!g" "$PROJECT_DIR/Makefile"

echo "Project $PROJECT_NAME created in $PROJECT_DIR"
echo "Use \`make' to build the project and \`make upload' to send it to your arduino"
